Adds mechanism to skip files from being moved.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,17 +1,53 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-# fail fast
-set -e
+################################################################################
+# Potherca Custom Heroku Boot script
+# ------------------------------------------------------------------------------
+# Sometimes the standards are just not what you need, so I am hacking my own.
+################################################################################
+
+
+
+################################################################################
+# CONFIG
+################################################################################
 
 # ==============================================================================
-# config
+# ------------------------------------------------------------------------------
+# fail fast
+set -e
+# ==============================================================================
+
+
+# ==============================================================================
+# The files in the project root we don't want moved to the root
+# ------------------------------------------------------------------------------
+declare -a aKeep
+aKeep+=('.buildpacks')
+aKeep+=('.profile.d')
+aKeep+=('vendor')
+aKeep+=('last_pack_release.out')
+# ==============================================================================
+
+# ==============================================================================
 # ------------------------------------------------------------------------------
 APACHE_VERSION="2.2.22"
 APACHE_PATH="apache"
+APACHE_URL="https://s3.amazonaws.com/php-lp/apache-$APACHE_VERSION.tar.gz"
+# ==============================================================================
+
+
+# ==============================================================================
+# ------------------------------------------------------------------------------
 PHP_VERSION="5.3.10"
 PHP_PATH="php"
+PHP_URL="https://s3.amazonaws.com/php-lp/php-$PHP_VERSION.tar.gz"
+# ==============================================================================
 
+
+# ==============================================================================
+# ------------------------------------------------------------------------------
 BIN_DIR=$(dirname $0)
 BUILD_DIR=$1
 CACHE_DIR=$2
@@ -20,13 +56,18 @@ LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
 
 
+################################################################################
+# FUNCTIONS
+################################################################################
+
 # ==============================================================================
-# Prepare for the action
+# Prepare for action
 # ------------------------------------------------------------------------------
 function preRun() {
     # include .files when moving things around
     shopt -s dotglob
 
+    # go to the start
     cd $BUILD_DIR
 }
 # ==============================================================================
@@ -37,7 +78,11 @@ function preRun() {
 # ------------------------------------------------------------------------------
 function moveAppToWebRoot() {
     mkdir -p $CACHE_DIR/www
-    mv * $CACHE_DIR/www
+
+    for sItem in $( ls ); do
+        in_array "${sItem}" "${aKeep[@]}" || mv "${sItem}" "${CACHE_DIR}/www"
+    done
+
     mv $CACHE_DIR/www .
 
     # keep Procfile
@@ -52,7 +97,6 @@ function moveAppToWebRoot() {
 # Install Apache
 # ------------------------------------------------------------------------------
 function installApache() {
-    APACHE_URL="https://s3.amazonaws.com/php-lp/apache-$APACHE_VERSION.tar.gz"
     echo "-----> Bundling Apache version $APACHE_VERSION"
     curl --silent --max-time 60 --location "$APACHE_URL" | tar xz
 # ==============================================================================
@@ -62,7 +106,6 @@ function installApache() {
 # Install PHP
 # ------------------------------------------------------------------------------
 function installPhp() {
-    PHP_URL="https://s3.amazonaws.com/php-lp/php-$PHP_VERSION.tar.gz"
     echo "-----> Bundling PHP version $PHP_VERSION"
     curl --silent --max-time 60 --location "$PHP_URL" | tar xz
 }
@@ -139,13 +182,12 @@ EOF
 function postRun() {
     # clean the cache
     rm -rf $CACHE_DIR/*
-}
+} 
 # ==============================================================================
 
 
-
 # ==============================================================================
-# Clean up after ourselves
+# On your places... Set... Go!
 # ------------------------------------------------------------------------------
 function run () {
     moveAppToWebRoot
