Adds the ability to detect the documentroot

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,5 +1,58 @@
 #!/usr/bin/env bash
+# bin/detect <BUILD_DIR>
 
-# No need for checks we need to always run
-echo "Potherca-PHP" && exit 0
+################################################################################
+#
+# ------------------------------------------------------------------------------
+################################################################################
 
+# ==============================================================================
+# CONFIG
+# ------------------------------------------------------------------------------
+# fail fast
+set -e
+# ==============================================================================
+
+BUILD_DIR=$1
+
+# ==============================================================================
+# Possible Directory Names for the DocumentRoot
+# ------------------------------------------------------------------------------
+declare -a aPossibleDocumentRoots
+
+aPossibleDocumentRoots+=('www')
+aPossibleDocumentRoots+=('web')
+aPossibleDocumentRoots+=('html')
+aPossibleDocumentRoots+=('public')
+# ==============================================================================
+
+
+################################################################################
+# FUNCTIONS
+################################################################################
+
+# ==============================================================================
+# Tries to find out if there is a public web dir
+# ------------------------------------------------------------------------------
+function detectDocumentRoot(){
+    bFound=false
+
+    for sDirectory in ${aPossibleDocumentRoots}; do
+        if [ -d "${BUILD_DIR}/${sDirectory}" ]; then
+            bFound=true
+            break
+        fi
+    done
+
+    if [ ${bFound} == true ]; then
+      echo "Potherca-PHP"
+      exit 0
+    else
+      exit 1
+    fi
+}
+# ==============================================================================
+
+detectDocumentRoot
+
+#EOF
